

columns = 'ASN_TYPE	PO_NUMBER	SHPD_DATE	PO_CANCEL_DATE	INVOICE_NO	INVOICE_DATE	GP Date	EXPECTED DELIVERY DATE	SHIP_VIA	TRAILER_NBR	DESTINATION_STORE_NUMBER 	UPC	Quantity	Selling_Price	TOTAL_COST_EX_VAT 	TOTAL_VAT'.split('\t')
print(columns)